--This file was autogenerated by the PostgreSQL. I made this so anyoane can have the aplication tables within this file.

--
-- PostgreSQL database dump
--

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 888 (class 1247 OID 16634)
-- Name: content_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.content_type AS ENUM (
    'text',
    'video',
    'pdf',
    'quiz'
);


--
-- TOC entry 894 (class 1247 OID 16652)
-- Name: proctoring_event; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.proctoring_event AS ENUM (
    'tab_switch',
    'full_screen_exit',
    'person_missing',
    'multiple_faces',
    'background_noise'
);


--
-- TOC entry 891 (class 1247 OID 16644)
-- Name: quiz_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.quiz_status AS ENUM (
    'started',
    'finished',
    'graded'
);


--
-- TOC entry 882 (class 1247 OID 16619)
-- Name: user_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_role AS ENUM (
    'student',
    'professor',
    'admin'
);


--
-- TOC entry 885 (class 1247 OID 16626)
-- Name: user_sex; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_sex AS ENUM (
    'male',
    'female',
    'other'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 241 (class 1259 OID 16881)
-- Name: class_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_members (
    id integer NOT NULL,
    class_id integer NOT NULL,
    student_id integer NOT NULL,
    joined_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 240 (class 1259 OID 16880)
-- Name: class_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.class_members_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5194 (class 0 OID 0)
-- Dependencies: 240
-- Name: class_members_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.class_members_id_seq OWNED BY public.class_members.id;


--
-- TOC entry 243 (class 1259 OID 16909)
-- Name: class_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_posts (
    id integer NOT NULL,
    class_id integer NOT NULL,
    author_id integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 242 (class 1259 OID 16908)
-- Name: class_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.class_posts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5195 (class 0 OID 0)
-- Dependencies: 242
-- Name: class_posts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.class_posts_id_seq OWNED BY public.class_posts.id;


--
-- TOC entry 239 (class 1259 OID 16862)
-- Name: classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classes (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    professor_id integer NOT NULL,
    join_code character varying(10) NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 238 (class 1259 OID 16861)
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.classes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5196 (class 0 OID 0)
-- Dependencies: 238
-- Name: classes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.classes_id_seq OWNED BY public.classes.id;


--
-- TOC entry 245 (class 1259 OID 16933)
-- Name: course_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_posts (
    id integer NOT NULL,
    course_id integer NOT NULL,
    author_id integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- TOC entry 244 (class 1259 OID 16932)
-- Name: course_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.course_posts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5197 (class 0 OID 0)
-- Dependencies: 244
-- Name: course_posts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.course_posts_id_seq OWNED BY public.course_posts.id;


--
-- TOC entry 225 (class 1259 OID 16711)
-- Name: coursecontent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coursecontent (
    id integer NOT NULL,
    course_id integer NOT NULL,
    content_types public.content_type[],
    data jsonb
);


--
-- TOC entry 224 (class 1259 OID 16710)
-- Name: coursecontent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.coursecontent_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5198 (class 0 OID 0)
-- Dependencies: 224
-- Name: coursecontent_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.coursecontent_id_seq OWNED BY public.coursecontent.id;


--
-- TOC entry 223 (class 1259 OID 16695)
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    professor_id integer,
    class_id integer
);


--
-- TOC entry 222 (class 1259 OID 16694)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.courses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5199 (class 0 OID 0)
-- Dependencies: 222
-- Name: courses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.courses_id_seq OWNED BY public.courses.id;


--
-- TOC entry 247 (class 1259 OID 25019)
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    event_date timestamp with time zone NOT NULL,
    class_id integer NOT NULL,
    professor_id integer NOT NULL
);


--
-- TOC entry 246 (class 1259 OID 25018)
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.events_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5200 (class 0 OID 0)
-- Dependencies: 246
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.events_id_seq OWNED BY public.events.id;


--
-- TOC entry 233 (class 1259 OID 16798)
-- Name: feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedback (
    id integer NOT NULL,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    result_id integer,
    comments text NOT NULL,
    rating integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 232 (class 1259 OID 16797)
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.feedback_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5201 (class 0 OID 0)
-- Dependencies: 232
-- Name: feedback_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.feedback_id_seq OWNED BY public.feedback.id;


--
-- TOC entry 237 (class 1259 OID 16844)
-- Name: module_resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.module_resources (
    id integer NOT NULL,
    module_id integer NOT NULL,
    title character varying(255) NOT NULL,
    file_type character varying(50),
    file_path text NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 16843)
-- Name: module_resources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.module_resources_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5202 (class 0 OID 0)
-- Dependencies: 236
-- Name: module_resources_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.module_resources_id_seq OWNED BY public.module_resources.id;


--
-- TOC entry 235 (class 1259 OID 16827)
-- Name: modules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modules (
    id integer NOT NULL,
    course_id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text
);


--
-- TOC entry 234 (class 1259 OID 16826)
-- Name: modules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.modules_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5203 (class 0 OID 0)
-- Dependencies: 234
-- Name: modules_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.modules_id_seq OWNED BY public.modules.id;


--
-- TOC entry 249 (class 1259 OID 25043)
-- Name: proctoring_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proctoring_sessions (
    id integer NOT NULL,
    quiz_id integer NOT NULL,
    student_id integer NOT NULL,
    leave_count integer DEFAULT 0,
    time_away_seconds double precision DEFAULT 0.0,
    face_not_found_warnings integer DEFAULT 0,
    multiple_faces_detected boolean DEFAULT false,
    speech_detected boolean DEFAULT false,
    ai_text_probability double precision DEFAULT 0.0,
    detailed_logs jsonb,
    trust_score integer DEFAULT 100,
    audio_transcript text
);


--
-- TOC entry 248 (class 1259 OID 25042)
-- Name: proctoring_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.proctoring_sessions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5204 (class 0 OID 0)
-- Dependencies: 248
-- Name: proctoring_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.proctoring_sessions_id_seq OWNED BY public.proctoring_sessions.id;


--
-- TOC entry 231 (class 1259 OID 16774)
-- Name: proctoringlogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proctoringlogs (
    id integer NOT NULL,
    result_id integer NOT NULL,
    student_id integer NOT NULL,
    event_type public.proctoring_event NOT NULL,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    details jsonb
);


--
-- TOC entry 230 (class 1259 OID 16773)
-- Name: proctoringlogs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.proctoringlogs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5205 (class 0 OID 0)
-- Dependencies: 230
-- Name: proctoringlogs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.proctoringlogs_id_seq OWNED BY public.proctoringlogs.id;


--
-- TOC entry 229 (class 1259 OID 16750)
-- Name: quizresults; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quizresults (
    id integer NOT NULL,
    quiz_id integer NOT NULL,
    student_id integer NOT NULL,
    start_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    finish_time timestamp with time zone,
    answers_json jsonb,
    final_score numeric(5,2),
    status public.quiz_status DEFAULT 'started'::public.quiz_status
);


--
-- TOC entry 228 (class 1259 OID 16749)
-- Name: quizresults_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.quizresults_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5206 (class 0 OID 0)
-- Dependencies: 228
-- Name: quizresults_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.quizresults_id_seq OWNED BY public.quizresults.id;


--
-- TOC entry 227 (class 1259 OID 16727)
-- Name: quizzes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quizzes (
    id integer NOT NULL,
    professor_id integer,
    title character varying(255) NOT NULL,
    time_allocated_minutes integer,
    quiz_data jsonb NOT NULL,
    course_id integer,
    enable_proctoring boolean DEFAULT false,
    start_time timestamp with time zone
);


--
-- TOC entry 226 (class 1259 OID 16726)
-- Name: quizzes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.quizzes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5207 (class 0 OID 0)
-- Dependencies: 226
-- Name: quizzes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.quizzes_id_seq OWNED BY public.quizzes.id;


--
-- TOC entry 221 (class 1259 OID 16681)
-- Name: userprofiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.userprofiles (
    id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(20),
    sex public.user_sex,
    address character varying(500),
    university character varying(255)
);


--
-- TOC entry 220 (class 1259 OID 16664)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    hashed_password character varying(255) NOT NULL,
    role public.user_role NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16663)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5208 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 4961 (class 2604 OID 16884)
-- Name: class_members id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members ALTER COLUMN id SET DEFAULT nextval('public.class_members_id_seq'::regclass);


--
-- TOC entry 4963 (class 2604 OID 16912)
-- Name: class_posts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_posts ALTER COLUMN id SET DEFAULT nextval('public.class_posts_id_seq'::regclass);


--
-- TOC entry 4959 (class 2604 OID 16865)
-- Name: classes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes ALTER COLUMN id SET DEFAULT nextval('public.classes_id_seq'::regclass);


--
-- TOC entry 4965 (class 2604 OID 16936)
-- Name: course_posts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_posts ALTER COLUMN id SET DEFAULT nextval('public.course_posts_id_seq'::regclass);


--
-- TOC entry 4947 (class 2604 OID 16714)
-- Name: coursecontent id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coursecontent ALTER COLUMN id SET DEFAULT nextval('public.coursecontent_id_seq'::regclass);


--
-- TOC entry 4946 (class 2604 OID 16698)
-- Name: courses id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses ALTER COLUMN id SET DEFAULT nextval('public.courses_id_seq'::regclass);


--
-- TOC entry 4967 (class 2604 OID 25022)
-- Name: events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events ALTER COLUMN id SET DEFAULT nextval('public.events_id_seq'::regclass);


--
-- TOC entry 4955 (class 2604 OID 16801)
-- Name: feedback id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback ALTER COLUMN id SET DEFAULT nextval('public.feedback_id_seq'::regclass);


--
-- TOC entry 4958 (class 2604 OID 16847)
-- Name: module_resources id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.module_resources ALTER COLUMN id SET DEFAULT nextval('public.module_resources_id_seq'::regclass);


--
-- TOC entry 4957 (class 2604 OID 16830)
-- Name: modules id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules ALTER COLUMN id SET DEFAULT nextval('public.modules_id_seq'::regclass);


--
-- TOC entry 4968 (class 2604 OID 25046)
-- Name: proctoring_sessions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoring_sessions ALTER COLUMN id SET DEFAULT nextval('public.proctoring_sessions_id_seq'::regclass);


--
-- TOC entry 4953 (class 2604 OID 16777)
-- Name: proctoringlogs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoringlogs ALTER COLUMN id SET DEFAULT nextval('public.proctoringlogs_id_seq'::regclass);


--
-- TOC entry 4950 (class 2604 OID 16753)
-- Name: quizresults id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizresults ALTER COLUMN id SET DEFAULT nextval('public.quizresults_id_seq'::regclass);


--
-- TOC entry 4948 (class 2604 OID 16730)
-- Name: quizzes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes ALTER COLUMN id SET DEFAULT nextval('public.quizzes_id_seq'::regclass);


--
-- TOC entry 4945 (class 2604 OID 16667)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 5005 (class 2606 OID 16892)
-- Name: class_members class_members_class_id_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT class_members_class_id_student_id_key UNIQUE (class_id, student_id);


--
-- TOC entry 5007 (class 2606 OID 16890)
-- Name: class_members class_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT class_members_pkey PRIMARY KEY (id);


--
-- TOC entry 5009 (class 2606 OID 16921)
-- Name: class_posts class_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_posts
    ADD CONSTRAINT class_posts_pkey PRIMARY KEY (id);


--
-- TOC entry 5001 (class 2606 OID 16874)
-- Name: classes classes_join_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_join_code_key UNIQUE (join_code);


--
-- TOC entry 5003 (class 2606 OID 16872)
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- TOC entry 5011 (class 2606 OID 16945)
-- Name: course_posts course_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_posts
    ADD CONSTRAINT course_posts_pkey PRIMARY KEY (id);


--
-- TOC entry 4987 (class 2606 OID 16720)
-- Name: coursecontent coursecontent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coursecontent
    ADD CONSTRAINT coursecontent_pkey PRIMARY KEY (id);


--
-- TOC entry 4985 (class 2606 OID 16704)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 5013 (class 2606 OID 25031)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- TOC entry 4995 (class 2606 OID 16810)
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- TOC entry 4999 (class 2606 OID 16855)
-- Name: module_resources module_resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.module_resources
    ADD CONSTRAINT module_resources_pkey PRIMARY KEY (id);


--
-- TOC entry 4997 (class 2606 OID 16837)
-- Name: modules modules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT modules_pkey PRIMARY KEY (id);


--
-- TOC entry 5015 (class 2606 OID 25060)
-- Name: proctoring_sessions proctoring_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoring_sessions
    ADD CONSTRAINT proctoring_sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 4993 (class 2606 OID 16786)
-- Name: proctoringlogs proctoringlogs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoringlogs
    ADD CONSTRAINT proctoringlogs_pkey PRIMARY KEY (id);


--
-- TOC entry 4991 (class 2606 OID 16762)
-- Name: quizresults quizresults_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizresults
    ADD CONSTRAINT quizresults_pkey PRIMARY KEY (id);


--
-- TOC entry 4989 (class 2606 OID 16738)
-- Name: quizzes quizzes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT quizzes_pkey PRIMARY KEY (id);


--
-- TOC entry 4983 (class 2606 OID 16688)
-- Name: userprofiles userprofiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.userprofiles
    ADD CONSTRAINT userprofiles_pkey PRIMARY KEY (id);


--
-- TOC entry 4977 (class 2606 OID 16680)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4979 (class 2606 OID 16676)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 16678)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 5034 (class 2606 OID 16927)
-- Name: class_posts fk_author_class; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_posts
    ADD CONSTRAINT fk_author_class FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5036 (class 2606 OID 16951)
-- Name: course_posts fk_author_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_posts
    ADD CONSTRAINT fk_author_course FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5032 (class 2606 OID 16893)
-- Name: class_members fk_class_mem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT fk_class_mem FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;


--
-- TOC entry 5035 (class 2606 OID 16922)
-- Name: class_posts fk_class_post; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_posts
    ADD CONSTRAINT fk_class_post FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;


--
-- TOC entry 5019 (class 2606 OID 16721)
-- Name: coursecontent fk_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coursecontent
    ADD CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- TOC entry 5020 (class 2606 OID 16744)
-- Name: quizzes fk_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- TOC entry 5029 (class 2606 OID 16838)
-- Name: modules fk_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- TOC entry 5017 (class 2606 OID 16903)
-- Name: courses fk_course_class; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk_course_class FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;


--
-- TOC entry 5037 (class 2606 OID 16946)
-- Name: course_posts fk_course_post; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_posts
    ADD CONSTRAINT fk_course_post FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- TOC entry 5038 (class 2606 OID 25032)
-- Name: events fk_event_class; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_event_class FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;


--
-- TOC entry 5039 (class 2606 OID 25037)
-- Name: events fk_event_professor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_event_professor FOREIGN KEY (professor_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5030 (class 2606 OID 16856)
-- Name: module_resources fk_module; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.module_resources
    ADD CONSTRAINT fk_module FOREIGN KEY (module_id) REFERENCES public.modules(id) ON DELETE CASCADE;


--
-- TOC entry 5040 (class 2606 OID 25061)
-- Name: proctoring_sessions fk_proctoring_quiz; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoring_sessions
    ADD CONSTRAINT fk_proctoring_quiz FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id) ON DELETE CASCADE;


--
-- TOC entry 5041 (class 2606 OID 25066)
-- Name: proctoring_sessions fk_proctoring_student; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoring_sessions
    ADD CONSTRAINT fk_proctoring_student FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5031 (class 2606 OID 16875)
-- Name: classes fk_prof_class; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT fk_prof_class FOREIGN KEY (professor_id) REFERENCES public.users(id);


--
-- TOC entry 5018 (class 2606 OID 16705)
-- Name: courses fk_professor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk_professor FOREIGN KEY (professor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5021 (class 2606 OID 16739)
-- Name: quizzes fk_professor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT fk_professor FOREIGN KEY (professor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5022 (class 2606 OID 16763)
-- Name: quizresults fk_quiz; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizresults
    ADD CONSTRAINT fk_quiz FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id) ON DELETE CASCADE;


--
-- TOC entry 5026 (class 2606 OID 16816)
-- Name: feedback fk_receiver; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fk_receiver FOREIGN KEY (receiver_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5024 (class 2606 OID 16787)
-- Name: proctoringlogs fk_result; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoringlogs
    ADD CONSTRAINT fk_result FOREIGN KEY (result_id) REFERENCES public.quizresults(id) ON DELETE CASCADE;


--
-- TOC entry 5027 (class 2606 OID 16821)
-- Name: feedback fk_result; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fk_result FOREIGN KEY (result_id) REFERENCES public.quizresults(id) ON DELETE SET NULL;


--
-- TOC entry 5028 (class 2606 OID 16811)
-- Name: feedback fk_sender; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5023 (class 2606 OID 16768)
-- Name: quizresults fk_student; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizresults
    ADD CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5025 (class 2606 OID 16792)
-- Name: proctoringlogs fk_student; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proctoringlogs
    ADD CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5033 (class 2606 OID 16898)
-- Name: class_members fk_student_mem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT fk_student_mem FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5016 (class 2606 OID 16689)
-- Name: userprofiles fk_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.userprofiles
    ADD CONSTRAINT fk_user FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE;


-- Completed on 2026-07-09 13:07:11

--
-- PostgreSQL database dump complete
--
